//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PB_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PB_USER()
        {
            this.PB_COMMENT = new HashSet<PB_COMMENT>();
            this.PB_LIKE = new HashSet<PB_LIKE>();
            this.PB_NOTIFICATION = new HashSet<PB_NOTIFICATION>();
            this.PB_NOTIFICATION1 = new HashSet<PB_NOTIFICATION>();
            this.PB_POST = new HashSet<PB_POST>();
            this.PB_POST1 = new HashSet<PB_POST>();
            this.PB_FRIENDS = new HashSet<PB_FRIENDS>();
            this.PB_FRIENDS1 = new HashSet<PB_FRIENDS>();
        }
    
        public int ID { get; set; }

        [Required]
        [DisplayName("Username")]
        [MaxLength(50,ErrorMessage = "The Username is too long, maximum length is 50.")]
        public string USER_NAME { get; set; }

        [Required]
        [DisplayName("Password")]
        [MaxLength(50, ErrorMessage = "The Password is too long, maximum length is 50.")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }

        public string SALT { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "The Firstname is too long, maximum length is 50.")]
        [DisplayName("Firstname")]
        [RegularExpression("^([A-Za-z0-9-' ]+$)?", ErrorMessage = "Invalid format, firstname can only contain alphanumeric characters,hyphen and apostrophe.")]
        public string FIRST_NAME { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "The Lastname is too long, maximum length is 50.")]
        [DisplayName("Lastname")]
        [RegularExpression("^([A-Za-z0-9-' ]+$)?", ErrorMessage = "Invalid format!!!!!, Lastname can only contain alphanumeric characters,hyphen and apostrophe.")]
        public string LAST_NAME { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",ApplyFormatInEditMode =true)]
        [DisplayName("Birthday")]
        public System.DateTime BIRTHDAY { get; set; }

        [DisplayName("Country")]
        public Nullable<int> COUNTRY_ID { get; set; }

        [DisplayName("Mobile No")]
        [MaxLength(50, ErrorMessage = "The Mobile No is too long, maximum length is 50.")]
        [DataType(DataType.PhoneNumber)]
        [Phone]
        public string MOBILE_NO { get; set; }

        [Required]
        [DisplayName("Gender")]
        public string GENDER { get; set; }

        [DisplayName("Profile Picture")]
        public byte[] PROFILE_PIC { get; set; }
        public System.DateTime DATE_CREATED { get; set; }

        [DisplayName("About Me")]
        [MaxLength(2000, ErrorMessage = "The About Me is too long, maximum length is 50.")]
        public string ABOUT_ME { get; set; }

        [Required]
        [DisplayName("Email Address")]
        [MaxLength(50, ErrorMessage = "The Email Address is too long, maximum length is 50.")]
        [EmailAddress]
        public string EMAIL_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_COMMENT> PB_COMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_LIKE> PB_LIKE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_NOTIFICATION> PB_NOTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_NOTIFICATION> PB_NOTIFICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_POST> PB_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_POST> PB_POST1 { get; set; }
        public virtual REF_COUNTRY REF_COUNTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_FRIENDS> PB_FRIENDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_FRIENDS> PB_FRIENDS1 { get; set; }
    }
}

